---
galaxy_info:
  author: Ruslan Starikov
  description: SSH hardening for Linux servers
  license: Unlicense
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - '7'
        - '8'
        - '9'
    - name: opensuse
      versions:
        - all
    - name: Amazon
      versions:
        - all

dependencies: []
